# Generated by Django 4.2.12 on 2025-04-05 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionoption',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
