# Generated by Django 4.2.12 on 2025-04-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
