# Generated by Django 4.2.12 on 2025-04-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_electionoption_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='ip_address',
        ),
    ]
