# Generated by Django 4.2.12 on 2025-04-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_vote_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
