# Generated by Django 4.2.12 on 2025-04-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_election_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
